import {Box, Container} from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Navbar } from '../components/navbar'
import PresentationView from '../components/home/presentation'
import FeaturesView from '../components/home/features'
import ExtensionView from '../components/home/extensions'
import FAQView from '../components/home/faq'


const App: NextPage = () => {
  return (
    <Box overflowX='hidden'>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth={{base:'100%', md: '90%', sm: '100%', lg: '70%'}} maxH="100%">
        <Navbar/>
        <Box p="5">
          <PresentationView/>
          <FeaturesView/>
          <ExtensionView/>
          <FAQView/>
        </Box>
      
      </Container>
    </Box>
  )
}

export default App;