import {Box, Container} from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Navbar } from '../components/navbar'
import PresentationView from '../components/home/presentation'
import FeaturesView from '../components/home/features'


const App: NextPage = () => {
  return (
    <Box position='relative' overflowX='hidden'>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container  maxW="90%" maxH="100%">
        <Navbar/>
        <Box p="5">
          <PresentationView/>
          <FeaturesView/>
        </Box>
      
      </Container>
    </Box>
  )
}

export default App;